"""Pillar guide content for LaunchStatic article generator."""

PILLAR_ARTICLES = [
    {
        "path": "/guides/static-landing-page-playbook.html",
        "meta_title": "Static Landing Page Playbook — Idea to Deploy for Indie Hackers",
        "meta_description": "A complete playbook for solo founders: validate your idea, write copy, pick a stack, ship a static landing page, and deploy without overbuilding.",
        "h1": "The Static Landing Page Playbook: From Idea to Deploy",
        "section": "Guides",
        "section_url": "/guides/",
        "date_display": "June 19, 2026",
        "read_time": "18 min read",
        "category": "Pillar Guide",
        "sections": [
            {"type": "p", "text": "Most indie products fail before anyone sees a landing page. Not because the idea is bad, but because founders spend weeks on authentication, dashboards, and billing before they have proof that strangers care. A static landing page flips that order. You ship a single HTML file (or a small folder of files), put it on a free host, and learn whether the problem and offer resonate. This playbook walks you through that path end to end—no framework churn, no premature SaaS architecture."},
            {"type": "p", "text": "Static does not mean amateur. Stripe, Linear, and plenty of YC companies launched on simple pages with a headline, three bullets, and an email field. The constraint is the feature: you are building a decision surface, not a product. Every section below maps to a decision you can make in an afternoon and ship the same week."},
            {"type": "h2", "text": "Phase 1: Clarify the bet before you open an editor"},
            {"type": "p", "text": "Start with one sentence: who hurts, what they do today, and what changes after your product exists. Example: \"Solo founders waste hours wiring waitlist forms; they need a deploy-ready static page with working signup in under ten minutes.\" If you cannot write that without jargon, the page will confuse visitors too. Write the sentence on paper. Sleep on it. That sentence becomes your hero subhead."},
            {"type": "p", "text": "Next, define the single primary action. For pre-launch, it is almost always email capture or calendar booking—not \"learn more\" scattered across five buttons. Secondary links (pricing FAQ, changelog) can wait. One CTA reduces bounce and makes analytics honest: did they sign up or not?"},
            {"type": "checklist", "items": [
                "I can name the visitor (role + context) in one line",
                "I wrote the before/after outcome without feature buzzwords",
                "Primary CTA is one action: join waitlist, book call, or download kit",
                "I know what I will do if fewer than 20 people sign up in two weeks",
                "I have a 48-hour ship deadline, not a \"when it's perfect\" deadline",
            ]},
            {"type": "h2", "text": "Phase 2: Structure that converts without a designer"},
            {"type": "p", "text": "High-performing static landers share a predictable scroll order: hero, social proof or problem agitation, how it works, objection handling, FAQ, final CTA. You do not need all seven on day one, but you do need hero + proof + CTA. Skipping proof is the most common solo-founder mistake: you assume the headline is self-evident. It is not. Add one concrete detail—time saved, error avoided, or a quote from a beta user."},
            {"type": "h3", "text": "Hero block"},
            {"type": "p", "text": "Headline: outcome, not category. Weak: \"Modern analytics platform.\" Strong: \"See which landing page copy actually drives signups.\" Subhead: expand who it is for and the mechanism in one breath. CTA button: verb + outcome (\"Join the waitlist\", \"Get the checklist\"). Under the button, one trust line: \"Free. No spam. Unsubscribe anytime.\" or \"Used by 40+ indie hackers in beta.\""},
            {"type": "h3", "text": "Body sections"},
            {"type": "ul", "items": [
                "Problem: describe the current workflow in visceral terms your reader recognizes",
                "Solution: three bullets max; each bullet starts with a verb",
                "How it works: three numbered steps; avoid architecture diagrams on v1",
                "Pricing teaser: even \"pricing TBD—early access discount for waitlist\" sets expectations",
                "FAQ: kill the top three objections you hear in DMs (security, lock-in, timeline)",
            ]},
            {"type": "p", "text": "Keep paragraphs short. On mobile, a four-line paragraph feels like a wall. One idea per paragraph. Use subheads every two screens so skimmers still get the story."},
            {"type": "h2", "text": "Phase 3: Pick a stack you can maintain alone"},
            {"type": "p", "text": "You need HTML, CSS, and a form endpoint. That is the whole production stack for v1. React, Astro, or Eleventy are fine if you already use them daily. If not, plain HTML plus a single CSS file ships faster and debugs faster at 2 a.m. when your form breaks. Bias toward what you can edit in VS Code and deploy with git push."},
            {"type": "table", "rows": [
                ["Option", "Best for", "Tradeoff"],
                ["Plain HTML + CSS", "Fastest ship, full control", "Manual includes for shared headers"],
                ["Eleventy / Hugo", "Multiple pages + blog later", "Build step to learn"],
                ["Astro", "Components without heavy JS", "Slightly more tooling"],
                ["Tailwind CDN", "Rapid layout experiments", "Harder to keep CSS tiny long-term"],
            ]},
            {"type": "p", "text": "Forms are the one dynamic piece. Use a hosted form backend (Formspree, Getform, Basin, or Cloudflare Workers + KV) so you never touch PHP or server admin. Wire the form action URL, add a honeypot field for bots, test from your phone on cellular—not just localhost."},
            {"type": "pre", "code": "<form action=\"https://formspree.io/f/your-id\" method=\"POST\">\n  <input type=\"email\" name=\"email\" required placeholder=\"you@company.com\">\n  <input type=\"text\" name=\"_gotcha\" style=\"display:none\" tabindex=\"-1\">\n  <button type=\"submit\">Join waitlist</button>\n</form>"},
            {"type": "h2", "text": "Phase 4: Copy and assets in one sitting"},
            {"type": "p", "text": "Block three hours. Hour one: headline and bullets from your bet sentence. Hour two: FAQ from real conversations or r/indiehackers posts in your niche. Hour three: visuals. Use one hero screenshot or illustration, not a carousel. Export WebP at 2x for retina; keep hero under 120 KB. Favicon and OG image are not optional—they affect trust when you paste the link in Slack or X."},
            {"type": "ol", "items": [
                "Draft copy in a doc, not directly in HTML—easier to edit and get feedback",
                "Read aloud; cut any sentence you stumble on",
                "Run Hemingway or similar once, then stop—perfectionism delays shipping",
                "Create 1200×630 OG image with headline text readable at thumbnail size",
                "Add alt text on every meaningful image for accessibility and SEO",
            ]},
            {"type": "h2", "text": "Phase 5: Performance and trust by default"},
            {"type": "p", "text": "Static pages should load in under two seconds on 4G. If they do not, you lose signups before the form renders. Defer non-critical JS. Inline critical CSS for above-the-fold content or keep total CSS under 15 KB. Self-host fonts or use system stacks. Lazy-load below-fold images. Add privacy policy and terms links in the footer before you run paid traffic—payment processors and ad platforms expect them."},
            {"type": "checklist", "items": [
                "Lighthouse performance score 90+ on mobile",
                "HTTPS on custom domain (not bare IP)",
                "Form success and error states tested",
                "404 page exists with link back to home",
                "Contact email or form linked in footer",
            ]},
            {"type": "h2", "text": "Phase 6: Deploy and verify"},
            {"type": "p", "text": "Connect GitHub to Cloudflare Pages or Netlify. Production branch: main. Build command: none for plain HTML, or npm run build for SSG. Set custom domain early so shared links use the real brand. After deploy, click every link, submit the form twice (duplicate handling), and view source to confirm meta tags. Set up uptime monitoring with a free ping service—silence is how you learn the site was down for a week."},
            {"type": "p", "text": "Tag the release in git. Screenshot the live page for your build-in-public thread. You are done when the URL is public and the form hits your inbox or spreadsheet."},
            {"type": "h2", "text": "Phase 7: Measure and iterate weekly"},
            {"type": "p", "text": "Track unique visitors, scroll depth if your analytics support it, and form submissions. Plausible or Fathom keeps you GDPR-friendly without cookie banners in many cases; Google Analytics 4 works if you configure consent. Calculate conversion rate: signups divided by unique visitors. Below 2% usually means message mismatch; above 8% on targeted traffic means you can narrow positioning."},
            {"type": "p", "text": "Change one variable per week: headline, hero image, CTA label, or social proof block. Keep a changelog in the repo README so you know what moved the needle. If traffic is zero, distribution is the problem—not the font. Post where your user already hangs out; do not wait for SEO on a brand-new domain."},
            {"type": "h2", "text": "Phase 8: Distribution the same day you deploy"},
            {"type": "p", "text": "A live URL is not launch. Block two hours for distribution the day you deploy. Post a short build log to communities where founders already discuss your problem—Indie Hackers, niche subreddits, Slack groups you genuinely participate in. Lead with the problem and one screenshot, not a product tour. Ask a specific question: \"Does this headline match how you'd describe the pain?\" Comments are copy research; upvotes are optional."},
            {"type": "p", "text": "Prepare three distribution assets in advance: a one-sentence pitch, a 280-character post, and a slightly longer LinkedIn or blog paragraph. Reuse the same CTA link everywhere so analytics stay clean. If you run small paid tests, cap spend until organic messaging converts. Fifty dollars on bad copy teaches less than ten honest replies from target users."},
            {"type": "ol", "items": [
                "Share in one community where you are a known participant, not a drive-by link drop",
                "Email five people who match your ICP and ask for a 60-second skim review",
                "Add the link to your X bio, GitHub profile, and email signature the same day",
                "Submit to one relevant directory only after the page has proof and FAQ",
                "Schedule a follow-up post seven days later with what you learned from signups",
            ]},
            {"type": "h2", "text": "A minimal file layout you can copy"},
            {"type": "p", "text": "Keep the repo boring. A typical v1 static landing project fits in five files: index.html, styles.css, favicon.ico, og-image.png, and robots.txt. Optional: privacy.html and terms.html linked from the footer. Store form configuration in HTML comments at the top of index.html so you remember which endpoint and list ID you used. Avoid nesting assets ten folders deep—you will mis-path images under stress."},
            {"type": "pre", "code": "project/\n  index.html\n  privacy.html\n  assets/\n    css/main.css\n    img/hero.webp\n    img/og.png\n  robots.txt\n  sitemap.xml"},
            {"type": "p", "text": "Version-control everything except secrets. API keys belong in your host environment or form provider dashboard, never committed. If you need A/B headlines later, duplicate index.html to index-b.html and split traffic with a simple redirect rule on your host—no need for a full experimentation framework on day one."},
            {"type": "h2", "text": "Common mistakes that waste a weekend"},
            {"type": "ul", "items": [
                "Building a blog before the landing page converts",
                "Custom CMS for content that changes monthly",
                "Embedding five analytics scripts that slow first paint",
                "Hiding pricing anxiety instead of addressing it in FAQ",
                "Using noreply@ as the only contact—signals \"don't talk to us\"",
                "Shipping desktop-only layouts; 60%+ of indie traffic is mobile",
            ]},
            {"type": "h2", "text": "When to graduate past a static page"},
            {"type": "p", "text": "Move to a dynamic app when you need authenticated dashboards, paid subscriptions with webhooks, or user-generated content. Until then, static plus a form backend and maybe a single serverless function handles waitlists, beta invites, and manual onboarding. The playbook goal is learning speed, not eternal stasis. Ship the static page this week; let data tell you what to build next."},
            {"type": "p", "text": "Bookmark this sequence as your default sprint: clarify bet, draft structure, pick plain HTML or familiar SSG, write copy in a doc, wire one form endpoint, deploy to Cloudflare Pages, verify on mobile, share in one community, measure for seven days, change one variable. Repeat until signups justify the next layer of product—not the other way around."},
        ],
        "faqs": [
            {"q": "How long should my first static landing page take to build?", "a": "A focused solo founder can ship in one to three days: day one for copy and structure, day two for HTML/CSS and form wiring, day three for domain, OG tags, and mobile polish. If you are past a week without traffic, you are overbuilding."},
            {"q": "Do I need a custom domain before sharing?", "a": "Not for friends-and-family feedback—a pages.dev subdomain is fine. For public launch, product directories, and paid ads, use a custom domain. It improves trust and makes email deliverability easier when you mail waitlist subscribers."},
            {"q": "What conversion rate should I expect on a waitlist page?", "a": "Cold traffic often lands at 1–3%. Warm communities (your newsletter, niche Discords) can hit 8–15%. Compare channels separately; one blended number hides what works."},
            {"q": "Plain HTML or a static site generator?", "a": "Plain HTML if you have one page and want the fewest moving parts. Use Eleventy or Hugo when you already plan multiple guides or changelog posts and want includes for header/footer without copy-paste."},
            {"q": "How do I collect emails without building a backend?", "a": "Point your form to Formspree, Basin, or a Cloudflare Worker that writes to Airtable or Google Sheets. Test submissions from an incognito window after deploy—cached success pages often hide broken endpoints."},
        ],
        "internal_links": [
            {"url": "/templates/", "text": "Landing page templates"},
            {"url": "/deploy-guides/", "text": "Deploy guides"},
            {"url": "/free-static-landing-kit/", "text": "Free static landing kit"},
            {"url": "/how-to/", "text": "Step-by-step how-tos"},
            {"url": "/tools/", "text": "Recommended tools"},
        ],
        "cta": {
            "title": "Ship your page this week",
            "text": "Grab a template, wire your form, and deploy to Cloudflare Pages in an afternoon. Momentum beats polish for your first validation loop.",
            "url": "/free-static-landing-kit/",
            "button": "Get the free kit",
            "secondary_url": "/templates/",
            "secondary_button": "Browse templates",
        },
    },
    {
        "path": "/guides/cloudflare-pages-complete-guide.html",
        "meta_title": "Cloudflare Pages Complete Guide — Deploy Static Sites for Indie Hackers",
        "meta_description": "Deep guide to Cloudflare Pages: project setup, custom domains, redirects, preview branches, forms, and production checklists for solo founders.",
        "h1": "Cloudflare Pages: The Complete Guide for Static Landing Pages",
        "section": "Guides",
        "section_url": "/guides/",
        "date_display": "June 19, 2026",
        "read_time": "20 min read",
        "category": "Pillar Guide",
        "sections": [
            {"type": "p", "text": "Cloudflare Pages gives indie hackers a fast path from git push to global CDN without managing servers. For a static landing page—HTML, CSS, a few images, and maybe a build step—it is often the best default: free tier is generous, SSL is automatic, and your site sits on the same network that blocks bots before they hit your origin. This guide assumes you are shipping a marketing or waitlist page, not a full-stack app. We cover setup, domains, previews, headers, redirects, and the mistakes that eat Saturdays."},
            {"type": "h2", "text": "What Cloudflare Pages is (and is not)"},
            {"type": "p", "text": "Pages is a static hosting product tied to Git. You connect a repository; Cloudflare clones it, runs an optional build command, and publishes the output directory to edge locations worldwide. It is not WordPress hosting, and it is not a database. Dynamic features—forms, search, auth—come from third-party services or Cloudflare Workers paired with Pages Functions. That separation is a feature: your landing page stays fast and cheap while you validate demand."},
            {"type": "ul", "items": [
                "Static assets: HTML, CSS, JS, images, fonts, PDFs",
                "SSG output: Eleventy, Hugo, Astro, Next static export, Vite build",
                "Preview deployments: every branch or PR gets a unique URL",
                "Custom domains: apex and www with automatic HTTPS",
                "Not included: long-running Node servers, MySQL, cron on the origin",
            ]},
            {"type": "h2", "text": "Prerequisites and account setup"},
            {"type": "p", "text": "Create a Cloudflare account and a GitHub (or GitLab) repository with your site files. If you use plain HTML, your repo root can be the deploy root. If you use a generator, commit package-lock or pnpm-lock so builds are reproducible. Turn on two-factor authentication on both Cloudflare and Git—your production marketing site should not be one stolen password away from defacement."},
            {"type": "checklist", "items": [
                "Cloudflare account with email verified",
                "Git repo with README noting build command and output folder",
                "Production branch named main (or adjust in settings)",
                "Local test: site opens correctly with npx serve or python -m http.server",
                "Form endpoint chosen and tested locally with curl or browser",
            ]},
            {"type": "h2", "text": "Create your first Pages project"},
            {"type": "ol", "items": [
                "In Cloudflare dashboard: Workers & Pages → Create → Pages → Connect to Git",
                "Authorize GitHub and select the repository",
                "Framework preset: None (or pick Astro/Hugo if applicable)",
                "Build command: leave empty for plain HTML; otherwise npm run build",
                "Build output directory: / for plain HTML; dist or _site or out for common SSGs",
                "Deploy and wait for the first green checkmark",
            ]},
            {"type": "p", "text": "Open the *.pages.dev URL on your phone over LTE. Check hero image, form, and tap targets. The first deploy is your baseline; screenshot Lighthouse scores now so you can compare after adding analytics or fonts."},
            {"type": "h3", "text": "Build settings for popular static stacks"},
            {"type": "table", "rows": [
                ["Stack", "Build command", "Output directory"],
                ["Plain HTML", "(none)", "/"],
                ["Vite", "npm run build", "dist"],
                ["Astro", "npm run build", "dist"],
                ["Hugo", "hugo", "public"],
                ["Eleventy", "npx @11ty/eleventy", "_site"],
                ["Next.js static", "npm run build", "out"],
            ]},
            {"type": "h2", "text": "Custom domains without DNS pain"},
            {"type": "p", "text": "Add your domain under Pages → Custom domains. If the domain already uses Cloudflare DNS, the CNAME or apex setup is mostly click-through. If DNS lives at Namecheap or Google Domains, either transfer DNS to Cloudflare (recommended for simplicity) or add the records Cloudflare shows you. Apex domains use CNAME flattening on Cloudflare; www should CNAME to your Pages project."},
            {"type": "p", "text": "Pick a canonical host: www or apex, not both without redirects. Duplicate URLs split SEO and confuse analytics. Set one as primary in Pages; add a redirect rule so the other permanently forwards. Wait for TLS certificates to reach Active status before posting the link publicly—first visitors remember certificate warnings."},
            {"type": "checklist", "items": [
                "Primary domain set in Pages settings",
                "Redirect www → apex (or apex → www) with 301",
                "HTTPS always; no mixed content warnings in browser console",
                "Update canonical link and OG:url tags to match primary host",
                "Old pages.dev URL still works; optional redirect to custom domain",
            ]},
            {"type": "h2", "text": "Environment variables and build secrets"},
            {"type": "p", "text": "If your build injects analytics IDs or public API endpoints, store them in Pages → Settings → Environment variables. Production and Preview can differ—use Preview without production keys when testing. Never embed private API secrets in client-side JS; anything in the built HTML is public. For waitlist forms, the form provider URL is fine in HTML; your admin API key is not."},
            {"type": "h2", "text": "Preview deployments for safe iteration"},
            {"type": "p", "text": "Every push to a non-production branch generates a preview URL. Use previews to share copy drafts with cofounders or beta users without touching production. Name branches after the experiment: headline-outcome-test, not fix-stuff. When you merge to main, production updates in usually under two minutes. Document preview URLs in PR descriptions so feedback stays traceable."},
            {"type": "h2", "text": "_redirects and _headers files"},
            {"type": "p", "text": "Cloudflare Pages honors Netlify-style _redirects and _headers in your publish directory. Put them in the output folder (often project root or dist). Redirects fix moved paths, force HTTPS variants, and send old campaign slugs to the homepage. Headers add security and caching without a Worker."},
            {"type": "pre", "code": "# _redirects\n/old-pricing /#pricing 301\nhttp://www.example.com/* https://example.com/:splat 301\n\n# _headers\n/*\n  X-Frame-Options: DENY\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n/assets/*\n  Cache-Control: public, max-age=31536000, immutable"},
            {"type": "p", "text": "Cache immutable hashed assets aggressively; keep HTML shorter cache or no-cache if you ship frequent copy tests. Misconfigured cache on HTML is why you \"deployed but still see old headline\"—purge CDN cache or bump a query string only as a last resort."},
            {"type": "h2", "text": "Forms, Functions, and where logic lives"},
            {"type": "p", "text": "Pure static forms POST to external endpoints—simplest and enough for waitlists. If you need custom validation, honeypot scoring, or Slack notifications, add a Pages Function in functions/api/submit.js that proxies to your backend. Keep functions small; cold starts are usually fine for form volume at indie scale. Log errors to console in preview, wire alerting only after you have paying customers."},
            {"type": "h2", "text": "Performance on Cloudflare by default"},
            {"type": "p", "text": "You already get HTTP/3, Brotli, and global anycast. Your job is not to defeat the CDN but to ship lean assets: responsive images, system or subset fonts, minimal third-party scripts. Use Cloudflare Web Analytics or Zaraz if you want lighter tracking. Each analytics script is another DNS lookup and parse cost on mobile."},
            {"type": "ol", "items": [
                "Compress hero image; prefer WebP or AVIF with PNG fallback if needed",
                "Load fonts with font-display: swap and limit weights to 2",
                "Defer non-critical JS; avoid jQuery for one toggle",
                "Preconnect only to domains you actually request",
                "Run Lighthouse in incognito after deploy, not only locally",
            ]},
            {"type": "h2", "text": "Security checklist for public marketing sites"},
            {"type": "checklist", "items": [
                "2FA on Cloudflare and Git provider",
                "Least-privilege GitHub app access—only repos that need deploy",
                "No secrets in repo; rotate if accidentally committed",
                "Security headers via _headers file",
                "Dependency updates for build tooling monthly",
                "Form spam: honeypot + provider-side filtering",
            ]},
            {"type": "h2", "text": "Troubleshooting deploy failures"},
            {"type": "p", "text": "Build fails: read the log line by line. Ninety percent are Node version mismatch, missing lockfile, or wrong output directory. Set NODE_VERSION in environment variables to match local. Site 404 after success: your index.html is not at the output root—fix output path or add index in public folder. Form works locally but not prod: mixed content (HTTP form on HTTPS site) or wrong action URL on production branch only."},
            {"type": "ul", "items": [
                "404 on all routes: wrong publish directory or missing index.html",
                "Assets 404: absolute paths like /assets/... break on preview subpaths—use relative or root-relative consistently",
                "Old content after deploy: HTML caching or browser cache—hard refresh or fix Cache-Control",
                "SSL pending: DNS not propagated; wait up to 24 hours, usually minutes on Cloudflare DNS",
                "Build OOM: reduce image sizes in repo or split large binaries to R2/external CDN",
            ]},
            {"type": "h2", "text": "Production launch day sequence"},
            {"type": "ol", "items": [
                "Merge final copy to main; confirm production deploy green",
                "Verify custom domain, www redirect, and SSL active",
                "Submit test form from mobile; confirm notification arrives",
                "Check robots.txt allows indexing; submit sitemap in Google Search Console",
                "Paste OG debugger URL for Slack/X/Twitter card preview",
                "Enable uptime monitor on apex and one deep link",
                "Tag release in git; note deploy time in changelog",
            ]},
            {"type": "p", "text": "Cloudflare Pages is infrastructure you configure once and forget for months. Invest an afternoon in domains, redirects, and headers so every future push is a one-click copy iteration—not another fire drill."},
            {"type": "h2", "text": "Wrangler CLI for power users"},
            {"type": "p", "text": "Wrangler lets you deploy without opening the dashboard—useful in CI or when you need a quick upload from a laptop at a café. Install with npm, authenticate once, then run pages deploy against your build output folder. Keep wrangler.toml in the repo with project name and compatibility flags documented. CLI deploys do not replace Git for day-to-day; they are escape hatches when GitHub is down or you need an emergency rollback asset."},
            {"type": "pre", "code": "npm i -g wrangler\nwrangler login\nwrangler pages deploy ./dist --project-name=my-landing"},
            {"type": "h2", "text": "Pairing Pages with R2 for large assets"},
            {"type": "p", "text": "If your repo balloons with PDFs, 4K screenshots, or demo videos, move binaries to R2 and reference public URLs in HTML. Smaller repos mean faster clones and builds. Set Cache-Control on R2 objects to match immutable assets. Keep HTML on Pages so copy deploys stay git-driven while heavy media ships separately."},
            {"type": "h2", "text": "Access control for client previews"},
            {"type": "p", "text": "Cloudflare Access can gate preview URLs behind email PIN or SSO when you share work-in-progress with design partners who should not see unfinished pricing. Production stays public. Document which branch triggers Access so you do not accidentally lock your homepage during a misconfigured rule experiment."},
            {"type": "h2", "text": "Monorepo and multiple projects"},
            {"type": "p", "text": "If marketing site and docs live in one repo, set build output to the marketing folder only or use a monorepo build script that outputs to dist. Separate Pages projects for docs versus marketing give independent deploy cadences—useful when docs need weekly churn but homepage changes monthly. Document which repo path maps to which project in README so future you does not wire the wrong branch."},
            {"type": "h2", "text": "Analytics without slowing Pages"},
            {"type": "p", "text": "Prefer lightweight analytics loaded async at end of body. Cloudflare Web Analytics adds minimal weight. If you need conversion goals, tag form submit success with a small inline script firing one event—avoid loading full GTM on a ten-field waitlist. Review network tab after each new embed; marketing people love tags that cost 400 KB."},
            {"type": "p", "text": "Save your final Pages settings in the repo as docs/DEPLOY.md: project name, build command, output dir, env vars, primary domain. Future collaborators should deploy without DMing you for screenshots of the dashboard."},
        ],
        "faqs": [
            {"q": "Is Cloudflare Pages free enough for a launch?", "a": "Yes for typical indie landing traffic. The free tier includes unlimited static requests and generous build minutes. You pay when you add paid Workers features, R2 at scale, or enterprise support—not for a waitlist page with modest traffic."},
            {"q": "Pages vs Workers: which do I need?", "a": "Pages alone for static HTML and SSG output. Add Workers or Pages Functions when you need edge logic—A/B redirects, form proxies, or lightweight APIs. Start without them."},
            {"q": "Can I deploy without Git?", "a": "Yes via Wrangler CLI direct upload for emergencies, but Git-connected deploys are the workflow you want for history, previews, and rollbacks."},
            {"q": "How do I roll back a bad deploy?", "a": "In Pages → Deployments, select a previous successful deployment and Retry deployment or Rollback to that version. Keep copy changes small so rollbacks are painless."},
            {"q": "Does Cloudflare replace my email or form tool?", "a": "No. Pages hosts files. Email capture still uses Formspree, Mailchimp embed, Buttondown API, or a Worker you write. DNS on Cloudflare can route email with MX records elsewhere."},
        ],
        "internal_links": [
            {"url": "/deploy-guides/", "text": "Deploy guides hub"},
            {"url": "/how-to/", "text": "How-to articles"},
            {"url": "/templates/", "text": "Static templates"},
            {"url": "/tools/", "text": "Tools directory"},
            {"url": "/free-static-landing-kit/", "text": "Free landing kit"},
        ],
        "cta": {
            "title": "Deploy on Cloudflare Pages today",
            "text": "Use our deploy guides and free kit to connect your repo, set a custom domain, and ship a waitlist-ready page without server admin.",
            "url": "/deploy-guides/",
            "button": "Open deploy guides",
            "secondary_url": "/free-static-landing-kit/",
            "secondary_button": "Download free kit",
        },
    },
    {
        "path": "/guides/indie-saas-prelaunch-strategy.html",
        "meta_title": "Indie SaaS Pre-Launch Strategy — Marketing for Solo Founders",
        "meta_description": "Pre-launch marketing playbook for solo founders: positioning, audience warming, waitlist loops, content cadence, and static-page tactics without a growth team.",
        "h1": "Indie SaaS Pre-Launch Strategy: Win Before You Ship Product",
        "section": "Guides",
        "section_url": "/guides/",
        "date_display": "June 19, 2026",
        "read_time": "19 min read",
        "category": "Pillar Guide",
        "sections": [
            {"type": "p", "text": "Pre-launch is not a countdown timer on a landing page. It is the work you do to make sure the right people feel a problem acutely—and trust you to solve it—before billing goes live. Solo founders lose here by copying enterprise playbooks: webinars, nurture sequences, partner ecosystems. You need a strategy that fits one person, a static site, and maybe twenty hours a week. This guide sequences positioning, audience, channels, and milestones so your launch is a continuation of conversations, not a cold start."},
            {"type": "h2", "text": "Define a narrow beachhead"},
            {"type": "p", "text": "Pre-launch marketing fails when the message speaks to everyone. Pick a beachhead: one role, one workflow, one acute pain. \"Project management for teams\" is a graveyard. \"Standup notes that sync to Linear for remote eng leads\" is a door. Your static landing page headline should make that beachhead nod, not scroll past."},
            {"type": "p", "text": "Write a positioning memo in 200 words: problem, alternative (spreadsheets, status quo), differentiated approach, proof you can deliver (your background, prototype screenshot, design partner quotes). Every tweet, DM, and FAQ answer should trace back to this memo. When you are tempted to add a feature bullet for a different persona, update the memo first or say no."},
            {"type": "checklist", "items": [
                "Beachhead user described with job title and weekly workflow",
                "Top three alternatives listed honestly—not strawmen",
                "One metric users care about (time, errors, revenue, stress)",
                "Reason to believe: demo GIF, testimonial, or your credible story",
                "Explicit non-goals: who this is not for",
            ]},
            {"type": "h2", "text": "Stages of pre-launch"},
            {"type": "table", "rows": [
                ["Stage", "Goal", "Primary asset"],
                ["Problem validation", "Confirm pain in their words", "Interviews + community posts"],
                ["Waitlist", "Capture intent and emails", "Static landing + form"],
                ["Nurture", "Stay top of mind without spam", "Email every 1–2 weeks"],
                ["Beta", "5–15 users on real workflow", "Manual onboarding doc"],
                ["Launch", "Convert waitlist + public push", "Pricing page + changelog"],
            ]},
            {"type": "p", "text": "Do not skip to paid ads before Problem validation. Ads amplify message; they do not invent fit. Two weeks of conversations in one subreddit or Slack often beats $500 in Meta spend with vague copy."},
            {"type": "h2", "text": "Build in public without building noise"},
            {"type": "p", "text": "Build in public works when you share decisions, metrics, and lessons—not repository commit counts. Post weekly: what you learned from users, what you cut from scope, what surprised you. Pair every post with a link to your waitlist only when the post delivers value standalone. Followers reward honesty about failures; they ignore \"Day 47 of coding my startup.\""},
            {"type": "ol", "items": [
                "Monday: ship one visible improvement (copy, screenshot, micro-demo)",
                "Wednesday: ask one question your beachhead would debate",
                "Friday: share a number—signups, churn risk, time saved in beta",
                "Keep a swipe file of verbatim user phrases; reuse in landing copy",
                "Reply to every waitlist signup within 24 hours early on—it sets tone",
            ]},
            {"type": "h2", "text": "Channel selection for one person"},
            {"type": "p", "text": "Pick two channels maximum until waitlist hits 200. Channel fit beats channel hype. B2B dev tools: X, Hacker News Show HN, niche Discords. Local SMB SaaS: Facebook groups, chambers, cold email with Loom. Creator tools: YouTube shorts, TikTok demos. Go where you already have reputation hours—not where a guru said you must be."},
            {"type": "ul", "items": [
                "Owned: landing page, email list, changelog on static site",
                "Earned: guest posts, podcast spots, community answers with depth",
                "Rented: X, LinkedIn, Reddit—algorithm changes; capture emails always",
                "Paid: retargeting waitlist visitors later; cold paid after message converts organically",
            ]},
            {"type": "h2", "text": "Waitlist as a product, not a email dump"},
            {"type": "p", "text": "Treat waitlist subscribers as early members. On signup, send immediate confirmation with what happens next and when. Segment by signup source (footer CTA vs blog post vs referral) using hidden form fields or UTM parameters stored in your spreadsheet. First nurture email within three days: story behind the product, not \"10% off coming soon.\""},
            {"type": "p", "text": "Offer one lightweight reward for engagement: template, audit checklist, or office hours slot for the first 50. Rewards should filter for serious users, not coupon hunters. A PDF that helps with the problem—even if your tool is not built yet—builds trust."},
            {"type": "h2", "text": "Content cadence on a static site"},
            {"type": "p", "text": "You do not need a daily blog. You need three durable pages: landing, one deep guide that ranks for a long-tail problem, and changelog or roadmap. Add posts when you have data or a story—not to satisfy an editorial calendar ghost. Static generators make adding /blog/my-lesson.html cheap; silence is better than filler."},
            {"type": "checklist", "items": [
                "Landing page CTA above fold on mobile",
                "One guide targets a specific search intent your user has pre-purchase",
                "Changelog shows momentum dates even if entries are small",
                "Internal links from guide to waitlist with contextual CTA",
                "Author bio or about page explains why you are credible",
            ]},
            {"type": "h2", "text": "Design partners before scale"},
            {"type": "p", "text": "Recruit five to ten design partners from waitlist volunteers who match the beachhead. Offer free lifetime tier or heavy discount in exchange for weekly 30-minute feedback and permission to quote them. Their language becomes your homepage. Their blockers become your sprint. Launch day testimonials write themselves if you did this work."},
            {"type": "p", "text": "Say no to partners outside the beachhead. A friendly enterprise IT director will pull your roadmap toward SSO and audit logs before you have ten users. Politely decline or park them on a separate list."},
            {"type": "h2", "text": "Metrics that matter pre-revenue"},
            {"type": "ul", "items": [
                "Waitlist signups per week by source",
                "Landing conversion rate by channel (do not blend)",
                "Email open and click rates on nurture sequence",
                "Design partner completion of key workflow tasks",
                "Unsolicited referrals or \"when can I pay\" messages",
            ]},
            {"type": "p", "text": "Vanity follower counts lag revenue. Signups and replies are leading indicators. If signups stall for three weeks while you build features, stop coding and fix distribution or positioning."},
            {"type": "h2", "text": "Pre-launch email sequence (five emails)"},
            {"type": "ol", "items": [
                "Day 0: Welcome—what you are building, timeline honesty, reply invitation",
                "Day 3: Problem story—your origin or a user story with permission",
                "Day 10: Behind the scenes—screenshot or Loom of current state",
                "Day 17: Ask—one multiple-choice question about priority feature",
                "Day 24: Beta invite or launch date with clear next step",
            ]},
            {"type": "p", "text": "Keep emails plain text or minimal HTML. No heavy images that trip spam filters. One link per email. Unsubscribe link is non-negotiable for trust and compliance."},
            {"type": "h2", "text": "Launch week coordination"},
            {"type": "p", "text": "Pick a Tuesday–Thursday launch day; avoid major holidays and US three-day weekends. Queue Show HN, Product Hunt, email blast, and social threads within the same four-hour window so momentum compounds. Prepare support: FAQ updated, inbox monitored, known bugs listed honestly on changelog. Sleep the night before—launch day is support and storytelling, not deploying auth."},
            {"type": "h2", "text": "Mistakes solo founders repeat"},
            {"type": "ul", "items": [
                "Launching product before landing page converts warm traffic",
                "Collecting emails without permission to contact or clear value",
                "Promising dates you miss—under-promise by weeks",
                "Competing on features against incumbents instead of wedge workflow",
                "Ignoring churn from waitlist unsubscribes as a messaging signal",
                "Building referral mechanics before base offer is clear",
            ]},
            {"type": "h2", "text": "Static-site tactics that compound"},
            {"type": "p", "text": "Add a /roadmap page with three columns: now, next, later. Public roadmaps reduce \"when will you build X\" emails and attract users who want transparency. Use /changelog for weekly bullets—even copy tweaks show velocity. Link both from footer and nurture emails. When you graduate to app, keep marketing static for speed; app subdomain for product."},
            {"type": "p", "text": "Pre-launch ends when strangers pay or actively use beta without hand-holding. Until then, your job is conversations at scale your sanity allows. The static landing page is the hub; everything else is spokes you maintain deliberately."},
            {"type": "h2", "text": "Budget and timeboxing"},
            {"type": "p", "text": "Solo pre-launch marketing should fit a realistic weekly budget: five to ten hours and under $100/month until conversion proves out. Spend money on email tooling and one professional OG image before ads. Track hours in a simple spreadsheet—if you spent twelve hours on logo tweaks and zero on user calls, rebalance."},
            {"type": "h2", "text": "Legal and compliance basics"},
            {"type": "p", "text": "Waitlist pages still need privacy policy explaining what you collect and how long you keep it. CAN-SPAM and GDPR principles apply even at small list sizes: clear sender, physical or business address in footer, working unsubscribe. Do not import LinkedIn scrapes into Mailchimp. Consent-based lists convert better at launch anyway."},
            {"type": "h2", "text": "Competitive teardown ritual"},
            {"type": "p", "text": "Monthly, screenshot three competitors' landers and note headline, CTA, proof, and pricing hints. You are not copying—you are mapping table stakes versus wedge. If everyone promises \"AI-powered,\" your wedge might be \"works offline\" or \"setup in four minutes.\" Save teardowns in /docs/competitors.md in your repo for positioning debates with future cofounders or advisors."},
            {"type": "ol", "items": [
                "Capture full-page screenshot on mobile and desktop",
                "Write their implied beachhead in one sentence",
                "List what they ask for at signup",
                "Note what they do not say—your FAQ opportunity",
                "Decide one deliberate difference for your next copy pass",
            ]},
            {"type": "h2", "text": "Community-led loops"},
            {"type": "p", "text": "Create a simple loop: teach in public → CTA to waitlist → welcome email asks one question → best answers become changelog or guide quotes → share update tagging contributors. Loops beat one-off viral posts because they compound trust. Static site hosts the CTA and changelog; community hosts the conversation—you bridge both."},
            {"type": "h2", "text": "Saying no to scope creep"},
            {"type": "p", "text": "Pre-launch DMs will request integrations you cannot ship before launch. Maintain a public \"not yet\" list on roadmap page instead of custom promises per DM. Polite template: \"Great idea—logged on roadmap vote. Launching core workflow first; I'll email waitlist when [integration] ships.\" Consistency protects launch date and your sanity."},
            {"type": "p", "text": "Record a two-minute Loom walking through the waitlist page and form once copy stabilizes. Reuse in emails when people ask what you are building—video beats paragraphs for busy founders. Keep the Loom unlisted and update quarterly so links in old threads stay accurate."},
            {"type": "p", "text": "Align pre-launch messaging with support capacity. If you are solo, promise human replies within 48 hours, not live chat 24/7. Under-promising response time on the static FAQ prevents one-star tweets at launch when inbox spikes."},
            {"type": "p", "text": "Batch creative work: refresh landing copy Monday, outreach Tuesday, product Wednesday, email Thursday, analytics Friday. Context switching between writing hero headlines and debugging API code in the same hour produces mediocre versions of both. Your static page deserves a focused editing block like any product feature—protect it on the calendar."},
        ],
        "faqs": [
            {"q": "How big should my waitlist be before launch?", "a": "Quality beats quantity. Fifty engaged signups from your beachhead beat 2,000 generic emails. Aim for consistent week-over-week growth and reply rates on nurture mail above 20% early on."},
            {"q": "Should I charge before the product is ready?", "a": "Lifetime deals or refundable pre-orders work for some niches; they require clear scope and refund policy. Many solo founders launch free beta first, then convert design partners to paid—simpler legally and operationally."},
            {"q": "Product Hunt on day one?", "a": "Only if landing page, onboarding, and support are ready for a traffic spike. Many indies do better with Show HN or community launch first, then PH when testimonials exist."},
            {"q": "How often should I email waitlist subscribers?", "a": "Every one to two weeks during build. Increase to twice a week only the seven days before launch. Silence for a month kills interest; daily pitches feel spammy."},
            {"q": "What if my niche community hates self-promotion?", "a": "Lead with teaching: threads, templates, teardowns. Put your link in bio and at the end after value. Ask moderators if unsure. Reputation takes longer but lasts."},
        ],
        "internal_links": [
            {"url": "/guides/waitlist-conversion-playbook.html", "text": "Waitlist conversion playbook"},
            {"url": "/templates/", "text": "Waitlist templates"},
            {"url": "/how-to/", "text": "How-to guides"},
            {"url": "/free-static-landing-kit/", "text": "Free landing kit"},
            {"url": "/tools/", "text": "Marketing tools"},
        ],
        "cta": {
            "title": "Start your pre-launch hub",
            "text": "Pair this strategy with a conversion-focused waitlist template and ship your static pre-launch site before the next feature sprint.",
            "url": "/templates/",
            "button": "Pick a template",
            "secondary_url": "/guides/waitlist-conversion-playbook.html",
            "secondary_button": "Optimize conversions",
        },
    },
    {
        "path": "/guides/waitlist-conversion-playbook.html",
        "meta_title": "Waitlist Conversion Playbook — Optimize Static Signup Pages",
        "meta_description": "Practical playbook to improve waitlist signup rates: hero copy, form UX, trust signals, A/B tests, and mobile fixes for static landing pages.",
        "h1": "The Waitlist Conversion Playbook for Static Landing Pages",
        "section": "Guides",
        "section_url": "/guides/",
        "date_display": "June 19, 2026",
        "read_time": "17 min read",
        "category": "Pillar Guide",
        "sections": [
            {"type": "p", "text": "Traffic without signups is a positioning problem wearing a design costume. Waitlist pages look simple—headline, form, done—but small frictions cut conversion in half: vague promise, four required fields, invisible mobile keyboard covering the button. This playbook is optimization for static pages you already deployed. No growth hacks that trade trust for clicks; just fixes you can ship in an evening and measure next week."},
            {"type": "h2", "text": "Diagnose before you redesign"},
            {"type": "p", "text": "Pull four numbers for the last 14 days: unique visitors, form views (if trackable), submissions, and traffic mix by source. Conversion rate = submissions / unique visitors. Segment mobile vs desktop. If mobile is under half your traffic but under a third of signups, layout or form UX is broken on small screens—not your offer."},
            {"type": "checklist", "items": [
                "Baseline conversion rate calculated per channel",
                "Mobile vs desktop split recorded",
                "Form error rate noted (validation failures, bounces on submit)",
                "Average scroll depth or time on page if analytics provide it",
                "Five session recordings or manual friend tests on real devices",
            ]},
            {"type": "h2", "text": "Hero: clarity beats cleverness"},
            {"type": "p", "text": "Visitors decide in three seconds. Headline must answer: what is it and who is it for? Subhead adds mechanism or timeframe. Avoid puns that hide the category. Test outcome headlines against problem headlines on the same traffic source—outcome often wins on warm traffic; problem can win on cold search intent."},
            {"type": "ul", "items": [
                "Headline under 12 words when possible",
                "Subhead mentions user role or situation",
                "Primary CTA visible without scrolling on 390px-wide viewport",
                "No competing buttons equal weight to join action",
                "Hero visual shows product UI or concrete result, not abstract stock art",
            ]},
            {"type": "h2", "text": "Form UX on static pages"},
            {"type": "p", "text": "Every field you add costs signups. Email-only is the default for waitlists. Name is optional second field if personalization matters. Never require phone or company size on v1. Use appropriate input types (email, tel) so mobile keyboards help. Label fields visibly; placeholder-only labels fail accessibility and usability."},
            {"type": "pre", "code": "<label for=\"email\">Work email</label>\n<input id=\"email\" name=\"email\" type=\"email\" autocomplete=\"email\" required>\n<button type=\"submit\">Join waitlist — it's free</button>\n<p class=\"fine\">One email at launch. Unsubscribe anytime.</p>"},
            {"type": "p", "text": "After submit, show inline success on the same page—do not redirect to a blank thank-you with no back link. Success copy confirms what happens next and when. If you use double opt-in, say check your inbox immediately. Failed submits must show actionable errors, not silent reload."},
            {"type": "h2", "text": "Trust without fake social proof"},
            {"type": "p", "text": "Real trust beats inflated counters. If you have 47 signups, say \"Join 47 teams on the waitlist\" only if true. Better: quote one design partner, show your face on about line, link privacy policy next to the form. Logos of companies \"using\" your product before launch erode trust when savvy visitors know you shipped last week."},
            {"type": "ol", "items": [
                "Link privacy policy and terms within one tap of the form",
                "Show founder name or photo with one-line credential",
                "Use specific beta quotes with first name and role",
                "Display security FAQ if you handle sensitive data eventually",
                "Avoid countdown timers unless deadline is real and enforced",
            ]},
            {"type": "h2", "text": "Objection handling on the page"},
            {"type": "p", "text": "FAQ is conversion copy disguised as help. Address: when launch, pricing ballpark, how data is used, integration with tools they already use, cancellation. Order FAQ by frequency in support DMs. Each answer ends with reassurance toward signup, not a sales cliffhanger."},
            {"type": "h3", "text": "FAQ templates you can adapt"},
            {"type": "ul", "items": [
                "When will it launch? — Honest quarter or month; explain what waitlist gets first",
                "How much will it cost? — Range or model; early-access discount for waitlist if true",
                "Is my email shared? — No; link privacy; mention provider (Buttondown, etc.)",
                "Can I use it with [tool]? — Yes/no/roadmap; specificity wins",
                "What if I need feature X at launch? — Reply to welcome email; you read feedback",
            ]},
            {"type": "h2", "text": "Mobile-specific fixes"},
            {"type": "p", "text": "Sticky nav eating vertical space pushes the CTA below fold. Shrink header on scroll or remove nav links on waitlist-only pages—logo and CTA suffice. Ensure button height at least 44px. Avoid horizontal scroll from wide code blocks or tables; stack them. Test autofill on iOS Safari; broken autocomplete frustrates power users."},
            {"type": "checklist", "items": [
                "Lighthouse mobile performance 85+",
                "Form and button full-width on narrow screens",
                "No intrusive cookie banner blocking submit on first visit",
                "Font size body 16px+ to prevent iOS zoom on focus",
                "Tap targets spaced; mis-taps kill completion",
            ]},
            {"type": "h2", "text": "Speed and conversion"},
            {"type": "p", "text": "Each second of delay on mobile costs completions. Defer analytics until after first paint if possible. Self-host critical CSS. Replace hero video with poster image on mobile. Lazy-load testimonial avatars. Speed is a trust signal—slow pages feel abandoned."},
            {"type": "h2", "text": "Structured experiments for solo founders"},
            {"type": "p", "text": "You do not need Optimizely. Change one element per week; record dates in README. Split traffic informally by channel: new headline to X traffic, old to email signature. After 200+ visits per variant, compare rates. Tests worth running: headline outcome, CTA verb (Join vs Get early access), social proof placement, form length, hero image product vs illustration."},
            {"type": "table", "rows": [
                ["Test", "Hypothesis", "Minimum sample"],
                ["Headline", "Outcome beats feature list", "200 visits per variant"],
                ["CTA label", "Specific benefit beats generic Join", "150 visits"],
                ["Email only vs email+name", "Fewer fields raise submits", "300 visits"],
                ["FAQ above vs below form", "Objections before ask help cold traffic", "250 visits"],
            ]},
            {"type": "h2", "text": "Post-signup experience drives referrals"},
            {"type": "p", "text": "Conversion continues after submit. Welcome email within minutes with share link or referral ask only if product is easy to explain. Asking for three referrals before they have used product feels gross. Better: deliver a useful PDF in welcome email; footer asks forward to one colleague who shares the pain."},
            {"type": "h2", "text": "When to add referral loops"},
            {"type": "p", "text": "Add referral mechanics after base conversion exceeds 5% on warm traffic and users spontaneously share. Static implementation: unique UTM per subscriber in email, manual leaderboard in public Notion, or lightweight referral tool embed. Reward early access tier movement, not cash lottery—indie SaaS audiences prefer status and access."},
            {"type": "h2", "text": "Red flags that look like optimization"},
            {"type": "ul", "items": [
                "Dark patterns: pre-checked marketing from unrelated brands",
                "Fake scarcity—\"only 3 spots\" that never changes",
                "Popups on entry before value is read",
                "Auto-playing video with sound",
                "Disabling back button or infinite exit intent modals",
                "Purchased email lists blasted to your form endpoint",
            ]},
            {"type": "p", "text": "Those tactics spike numbers briefly and poison brand. Indie SaaS lives on trust and word of mouth. Optimize for qualified signups from people who would be disappointed if you never shipped."},
            {"type": "h2", "text": "Weekly optimization ritual"},
            {"type": "ol", "items": [
                "Monday: review conversion by source; pick one weak channel",
                "Tuesday: ship one copy or layout fix; deploy via git",
                "Wednesday: read five signup notification emails—any corporate domains to note",
                "Thursday: send one value email to list; measure clicks",
                "Friday: document what changed and rate next week",
            ]},
            {"type": "p", "text": "Waitlist optimization is never finished; it pauses when you launch and talk to users daily. Until then, treat the page as a measurable instrument—not a brochure you set once."},
            {"type": "h2", "text": "Copy formulas that stay honest"},
            {"type": "p", "text": "Use formulas as scaffolding, not mad libs. Outcome headline: \"[Achieve outcome] without [painful alternative].\" Proof line: \"[Number or quote] from [credible source].\" CTA: verb + what they get + friction reducer (\"Join waitlist — free, 30 seconds\"). Swap components; keep truth. If you cannot fill a slot without lying, fix the product story."},
            {"type": "h2", "text": "Accessibility lifts conversion too"},
            {"type": "p", "text": "Semantic labels, focus states on inputs, sufficient color contrast, and keyboard-submit support help everyone and reduce mobile errors. Screen reader users are founders and buyers too. An accessible form is usually a clearer form—visible labels, logical tab order, error text tied to fields with aria-describedby."},
            {"type": "h2", "text": "International visitors"},
            {"type": "p", "text": "If analytics show UK or EU traffic, mention GDPR-friendly practices near the form and avoid pre-checked marketing consents. Plain English copy helps non-native readers; idioms and slang in headlines confuse cold international traffic. Consider spelling variants only when you localize a whole page—not random mixed spellings."},
            {"type": "checklist", "items": [
                "Visible focus ring on inputs and button",
                "Error messages announced to assistive tech",
                "Contrast ratio 4.5:1 on body text",
                "Language attribute set on html element",
                "Motion respects prefers-reduced-motion for animations",
            ]},
            {"type": "h2", "text": "Recovering from a conversion dip"},
            {"type": "p", "text": "Sudden drops often trace to deploy regressions—broken form action, SSL mixed content, or analytics blocking render—not mystical market shifts. Compare last deploy diff. Roll back on Pages if needed. If form works but rate fell, check whether traffic source mix changed. A viral low-intent post tanks blended rate while email still converts—segment before panic redesign."},
            {"type": "h2", "text": "Above-the-fold layout patterns"},
            {"type": "p", "text": "Two patterns work for static waitlists: centered single column (headline, subhead, form, fine print) and split column (copy left, form right on desktop, stacked mobile). Centered converts well for single-message offers; split helps when you need three proof bullets beside the ask. Never put the form only in a modal triggered by a generic Learn more button."},
            {"type": "h2", "text": "Thank-you state and onboarding"},
            {"type": "p", "text": "Inline thank-you should repeat timeline and invite reply with use case. Optional second step: ask one multiple-choice question to segment nurture. Do not require another account signup on thank-you—that feels like bait-and-switch. If you promise a lead magnet, deliver link immediately on screen and in email."},
            {"type": "h2", "text": "Heatmaps and qual data on a budget"},
            {"type": "p", "text": "Microsoft Clarity is free and works on static pages—use sparingly, review recordings weekly, and mask email fields. Five recordings often reveal rage clicks on disabled buttons or footer links stealing attention. Pair with one open question in welcome email: \"What made you sign up today?\" Answers beat heatmaps for why."},
            {"type": "ul", "items": [
                "Log verbatim signup answers in spreadsheet tags",
                "Tag subject lines in welcome sequence by signup source",
                "Revisit FAQ when same question appears three times",
                "Promote best user phrase to headline test variant",
                "Archive losing variants in git, not delete—reuse later",
            ]},
            {"type": "p", "text": "Sync waitlist page CTA with email signatures, social bios, and community profiles within one day of headline changes. Stale links with old UTM still work but split test data and confuse returning visitors who remember different promise."},
            {"type": "p", "text": "Review notification emails for corporate domains—they signal ICP fit even before nurture replies. A waitlist full of personal Gmail is fine for B2C; for B2B, celebrate when design leads from target companies appear and ask what nearly stopped them from signing up. Log objections verbatim; they become FAQ bullets that lift conversion on the next weekly deploy cycle without a full redesign."},
        ],
        "faqs": [
            {"q": "What is a good waitlist conversion rate?", "a": "2–5% on mixed organic traffic is common. 8%+ on targeted communities is healthy. Below 1% on warm traffic means rewrite hero and FAQ before buying ads."},
            {"q": "Should the form be in the hero or at the bottom?", "a": "Hero for single-purpose waitlist pages. Long educational pages can repeat CTA mid-page and bottom—but never hide the only form below 3,000 words without mid-page CTA."},
            {"q": "Double opt-in or single?", "a": "Double opt-in improves list quality and compliance in EU contexts; single captures more emails. If you double opt-in, confirmation page must explain the value of confirming."},
            {"q": "How do I reduce bot signups?", "a": "Honeypot field, provider CAPTCHA if spam spikes, and block disposable email domains in your form tool if available."},
            {"q": "One page or separate /waitlist route?", "a": "One page is simpler for v1. Use /waitlist when homepage becomes multi-product or blog-heavy and you need a dedicated campaign landing URL."},
        ],
        "internal_links": [
            {"url": "/templates/waitlist.html", "text": "Waitlist template"},
            {"url": "/guides/indie-saas-prelaunch-strategy.html", "text": "Pre-launch strategy"},
            {"url": "/how-to/", "text": "How-to guides"},
            {"url": "/tools/", "text": "Form and analytics tools"},
            {"url": "/free-static-landing-kit/", "text": "Free landing kit"},
        ],
        "cta": {
            "title": "Lift conversions this week",
            "text": "Start from a waitlist template built for fast forms and mobile-first layout, then apply one playbook test per week.",
            "url": "/templates/waitlist.html",
            "button": "Use waitlist template",
            "secondary_url": "/free-static-landing-kit/",
            "secondary_button": "Get free kit",
        },
    },
    {
        "path": "/guides/static-site-seo-handbook.html",
        "meta_title": "Static Site SEO Handbook — Sitemap, Schema, Core Web Vitals",
        "meta_description": "SEO handbook for static landing pages and indie sites: indexing, sitemaps, structured data, meta tags, internal links, and Core Web Vitals without WordPress plugins.",
        "h1": "Static Site SEO Handbook: Rank Without a CMS",
        "section": "Guides",
        "section_url": "/guides/",
        "date_display": "June 19, 2026",
        "read_time": "21 min read",
        "category": "Pillar Guide",
        "sections": [
            {"type": "p", "text": "Static sites are SEO-friendly by default: fast HTML, no database timeouts, small attack surface. They are also easy to get wrong because nobody installs an SEO plugin to nag you. You hand-write meta tags once, forget sitemap.xml, and wonder why Google shows a blank description. This handbook covers technical SEO for indie static landers and small content sites—sitemap, robots, schema, CWV, and internal linking—without enterprise tooling."},
            {"type": "h2", "text": "How search engines see your static site"},
            {"type": "p", "text": "Crawlers fetch URLs, parse HTML, follow links, and index what they can render. Static HTML is ideal: content is in the response, not behind client-side routing that delays paint. JavaScript-heavy SPAs without prerender still rank, but slower and flakier. For marketing pages, ship real HTML files per URL."},
            {"type": "ul", "items": [
                "Each important URL returns 200 with unique title and description",
                "Canonical tag points to preferred URL version",
                "Internal links use normal anchor hrefs crawlers can follow",
                "Noindex only on thank-you, staging, or duplicate thin pages",
                "HTTPS everywhere; redirects consolidate www/apex",
            ]},
            {"type": "h2", "text": "Essential meta tags on every page"},
            {"type": "p", "text": "Title: primary keyword near front, brand at end, under 60 characters displayed. Meta description: compelling summary, not keyword stuffing, 150–160 characters. One H1 matching search intent. Open Graph and Twitter tags for share previews—social clicks indirectly support discovery even if not ranking factors."},
            {"type": "pre", "code": "<title>Waitlist Landing Page Template — LaunchStatic</title>\n<meta name=\"description\" content=\"Deploy-ready waitlist page for indie hackers. Fast HTML, form-ready, mobile-first.\">\n<link rel=\"canonical\" href=\"https://launchstatic.dev/templates/waitlist.html\">\n<meta property=\"og:title\" content=\"Waitlist Landing Page Template\">\n<meta property=\"og:description\" content=\"Ship a waitlist page this afternoon.\">\n<meta property=\"og:image\" content=\"https://launchstatic.dev/assets/img/og/waitlist.png\">\n<meta name=\"twitter:card\" content=\"summary_large_image\">"},
            {"type": "h2", "text": "robots.txt and crawl budget"},
            {"type": "p", "text": "At indie scale, crawl budget is rarely the bottleneck—indexation and relevance are. Still, robots.txt should allow public content and point to sitemap. Do not block CSS/JS; Google needs them to render. Staging previews on pages.dev can use noindex meta or HTTP auth; do not leak duplicate content on indexable URLs."},
            {"type": "pre", "code": "User-agent: *\nAllow: /\nSitemap: https://launchstatic.dev/sitemap.xml"},
            {"type": "h2", "text": "sitemap.xml that stays current"},
            {"type": "p", "text": "List canonical URLs you want indexed. Omit noindex pages, redirects, and 404s. Include lastmod if you maintain it—honest dates help recrawl after updates. For ten-page sites, hand-maintain sitemap. For blogs, generate at build time with your SSG or a small script in CI."},
            {"type": "ol", "items": [
                "Homepage, key landing pages, guides, templates index",
                "Legal pages optional; low priority",
                "Submit sitemap in Google Search Console and Bing Webmaster Tools",
                "Regenerate sitemap when adding routes; redeploy same commit",
                "Keep under 50,000 URLs—irrelevant for indies but good habit",
            ]},
            {"type": "h2", "text": "Structured data (schema.org)"},
            {"type": "p", "text": "JSON-LD in script tags is the cleanest for static sites. Article schema for guides; FAQPage for FAQ sections; Organization on homepage; WebSite with SearchAction only if you have on-site search. Validate with Google Rich Results Test after deploy—not just locally."},
            {"type": "pre", "code": "<script type=\"application/ld+json\">\n{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Article\",\n  \"headline\": \"Static Site SEO Handbook\",\n  \"description\": \"SEO for static landing pages.\",\n  \"author\": {\"@type\": \"Organization\", \"name\": \"LaunchStatic\"},\n  \"datePublished\": \"2026-06-19\",\n  \"mainEntityOfPage\": \"https://launchstatic.dev/guides/static-site-seo-handbook.html\"\n}\n</script>"},
            {"type": "p", "text": "FAQ schema can yield rich snippets; questions must appear on page verbatim. Do not mark up invisible content. BreadcrumbList helps sitelinks clarity in some cases—match visible breadcrumb nav."},
            {"type": "h2", "text": "URL structure and information architecture"},
            {"type": "p", "text": "Readable paths beat opaque IDs: /guides/waitlist-conversion-playbook.html beats /p?id=17. Keep folders shallow. Trailing slash consistency matters—pick one via redirects. Use hyphens in filenames. Lowercase only."},
            {"type": "table", "rows": [
                ["Pattern", "Example", "Note"],
                ["Hub + leaf", "/guides/seo-handbook.html", "Breadcrumb back to /guides/"],
                ["Templates", "/templates/waitlist.html", "Commercial intent pages"],
                ["Blog", "/blog/deploy-cloudflare.html", "Date optional in URL"],
                ["Avoid", "/page/v2/final-real.html", "Signals churn to users and bots"],
            ]},
            {"type": "h2", "text": "Internal linking strategy"},
            {"type": "p", "text": "Static sites lack sidebar widgets unless you build them. Plan links in content: every guide links to two related guides, one template, one tool. Hub pages (/guides/, /templates/) list children with descriptive anchor text—not \"click here.\" Footer links repeat key hubs. Internal links distribute authority and help discovery without sitemap alone."},
            {"type": "checklist", "items": [
                "Each new page linked from at least one existing indexed page",
                "Anchor text describes destination (waitlist template, not read more)",
                "Orphan pages audit quarterly—Search Console coverage report",
                "Related links block at end of articles",
                "Breadcrumb nav matches URL hierarchy",
            ]},
            {"type": "h2", "text": "Core Web Vitals on static HTML"},
            {"type": "p", "text": "LCP (Largest Contentful Paint): optimize hero image dimensions and priority hint. INP (Interaction to Next Paint): minimize main-thread JS on form pages. CLS (Cumulative Layout Shift): width/height on images, reserve space for web fonts, avoid injecting banners above content late."},
            {"type": "ul", "items": [
                "LCP: preload hero WebP; serve from CDN; avoid lazy-load on LCP image",
                "INP: defer third-party scripts; small inline handlers only",
                "CLS: font-display swap with metric-matched fallbacks",
                "TTFB: Cloudflare caching; HTML not over-cached during copy tests",
                "Measure field data in Search Console CWV report after traffic exists",
            ]},
            {"type": "h2", "text": "Content that earns links and rankings"},
            {"type": "p", "text": "Technical SEO gets you indexed; content gets you ranked. For indies, long-tail guides that solve one problem completely outperform thin \"best tools 2026\" listicles. Original screenshots, step-by-step deploy commands, and checklists attract links from forums. Update posts when APIs change—lastmod in sitemap signals freshness."},
            {"type": "h2", "text": "International and duplicate content"},
            {"type": "p", "text": "If you ship /en/ and root English duplicate, canonical one version. hreflang only when you have real translations—not machine spam. Parameterized URLs for UTM are fine; canonical without params on marketing pages."},
            {"type": "h2", "text": "Google Search Console workflow"},
            {"type": "ol", "items": [
                "Verify domain property via DNS TXT",
                "Submit sitemap.xml",
                "Inspect URL after major copy deploy; request indexing sparingly",
                "Monitor Coverage and Page Experience reports monthly",
                "Fix soft 404s—pages with little content that return 200",
                "Review queries report for unexpected keywords to support with content",
            ]},
            {"type": "h2", "text": "Bing and secondary engines"},
            {"type": "p", "text": "Bing Webmaster Tools import from GSC in minutes. DuckDuckGo uses Bing index. Neglecting Bing costs little traffic in US/EU SaaS but setup is ten minutes—worth it."},
            {"type": "h2", "text": "Local SEO if relevant"},
            {"type": "p", "text": "Local service SaaS needs NAP consistency, Google Business Profile, and LocalBusiness schema. Pure global B2B tools skip local schema—do not fake addresses."},
            {"type": "h2", "text": "SEO mistakes on static landers"},
            {"type": "ul", "items": [
                "Identical title/description on every page",
                "Missing canonical when syndicating same kit to multiple paths",
                "Blocking entire site in staging robots.txt copied to production",
                "Huge unoptimized PNG heroes crushing LCP",
                "No analytics on which landing URLs convert—SEO without conversion feedback",
                "Buying links or AI mass pages—short-term poison",
            ]},
            {"type": "h2", "text": "Maintenance calendar"},
            {"type": "p", "text": "Monthly: broken link check, Search Console errors, dependency bumps for build. Quarterly: refresh top guide stats and screenshots, internal link audit, CWV lab test. At launch: full technical pass; after that, SEO is incremental—not a one-week project."},
            {"type": "p", "text": "Static SEO is discipline, not plugins. Ship clean HTML, keep sitemap honest, write one great page per intent, and let speed work in your favor while bigger competitors load analytics suites."},
            {"type": "h2", "text": "Image SEO and media"},
            {"type": "p", "text": "Name files descriptively: waitlist-hero-dashboard.webp not IMG_8842.png. Write alt text describing the image function, not keyword dumps. Use picture element for WebP with fallback. Host large PDFs with clear link text; optional PDF schema only if you invest in maintaining metadata."},
            {"type": "h2", "text": "Pagination and archive pages"},
            {"type": "p", "text": "Blog indexes listing ten posts per page need rel=next/prev or a single view-all if small. Avoid infinite scroll without crawlable links—bots may not see deep posts. Static generators often handle this; plain HTML bloggers should add manual next links."},
            {"type": "h2", "text": "Monitoring rankings without obsession"},
            {"type": "p", "text": "Track five to ten target queries in Search Console, not third-party rank trackers daily. Month-over-month impression growth on intended queries matters more than position three vs five. Note SERP feature changes—FAQ rich results, AI overviews— and adapt content format when clicks shift."},
            {"type": "h2", "text": "Security headers and SEO"},
            {"type": "p", "text": "Headers do not directly rank you, but HSTS and CSP reduce compromise risk that nukes trust if site gets defaced. After adding strict CSP, test forms and analytics in staging—broken scripts do not hurt rankings but hurt conversions you measure from organic."},
            {"type": "pre", "code": "# Example CSP snippet—tune per your embeds\nContent-Security-Policy: default-src 'self'; script-src 'self' plausible.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; form-action 'self' https://formspree.io"},
            {"type": "h2", "text": "Launch checklist: technical SEO"},
            {"type": "checklist", "items": [
                "Unique title and meta description per URL",
                "Canonical matches live primary domain",
                "sitemap.xml submitted and fetchable",
                "robots.txt allows CSS/JS and points to sitemap",
                "JSON-LD validates without errors",
                "Mobile-friendly test passes",
                "No accidental noindex on production",
                "404 returns proper status, not soft redirect to home",
                "Internal links from home to money pages",
                "OG image returns 200 and correct dimensions",
            ]},
            {"type": "p", "text": "Revisit this checklist after every major IA change—adding /guides/, splitting templates, or migrating hosts. Static sites make diffs obvious in git; use that audit trail when rankings wobble after a refactor."},
            {"type": "h2", "text": "Programmatic pages without spam"},
            {"type": "p", "text": "Indies sometimes generate location or integration pages from JSON at build time. That is fine when each page has unique utility—setup steps for that integration—not 200 near-duplicate paragraphs. Cap programmatic pages at what you can maintain. One excellent /integrations/linear.html beats fifty thin stubs."},
            {"type": "h2", "text": "Page speed budgets"},
            {"type": "p", "text": "Set a budget: HTML under 50 KB, total page weight under 500 KB on landing, requests under 30 on first load. Measure in WebPageTest from a mobile profile quarterly. Exceeding budget triggers a trim sprint—drop a font weight, compress hero, remove an embed—not a redesign."},
            {"type": "h2", "text": "Fixing indexation drops"},
            {"type": "p", "text": "If indexed pages fall suddenly, check robots.txt deploy, accidental noindex meta, 5xx during crawl, or domain migration without redirects. Search Console URL Inspection shows live Google view. Keep old URLs 301ing for at least a year after migrations; static sites make redirect maps easy in _redirects."},
            {"type": "ol", "items": [
                "Compare sitemap URL count to indexed count monthly",
                "Fetch robots.txt in browser after each production deploy",
                "Run site:yourdomain.com monthly for obvious omissions",
                "Fix broken internal links found in Screaming Frog free tier crawl",
                "Add contextual links from high-traffic posts to new guides",
            ]},
            {"type": "p", "text": "SEO for static indies is a slow compounding channel alongside community launch. Technical hygiene keeps the door open; useful guides and templates bring visitors who actually sign up. Pair this handbook with conversion work on the same URLs—rankings without signups is a hobby, not distribution."},
            {"type": "p", "text": "When you add new guides under /guides/, update the hub page HTML and sitemap the same commit. Hub pages pass internal PageRank to leaf articles; orphan guides without hub links can lag indexation for weeks on new domains."},
            {"type": "p", "text": "Track organic landing URLs in the same spreadsheet as waitlist conversion. A guide ranking on page one with 0.5% signup rate needs a stronger CTA block, not more backlinks. SEO and conversion optimization on static sites share the same HTML files—treat them as one system."},
            {"type": "p", "text": "Prefer stable URLs when updating titles. A renamed filename without 301 loses accumulated signals. Edit in place when possible; redirect old paths when you must restructure. Static repos make filename churn tempting—resist for any URL that already earned impressions in Search Console."},
            {"type": "p", "text": "Add last-updated visible dates on guides when facts change. Users and crawlers both reward maintained references; stale year references in titles erode click-through without you noticing."},
        ],
        "faqs": [
            {"q": "Do static sites rank as well as WordPress?", "a": "Yes for comparable content and technical quality. WordPress adds convenience plugins; static adds speed and control. Rankings follow relevance, links, and experience signals—not CMS brand."},
            {"q": "How long until new pages get indexed?", "a": "Days to weeks depending on authority. Request indexing once after publish; focus on internal links and sharing to speed discovery."},
            {"q": "Do I need a blog for SEO?", "a": "Not mandatory. One strong guide plus template pages can rank. Add blog posts when you have unique data or tutorials—not filler."},
            {"q": "Should I use trailing slashes?", "a": "Either works if consistent. Redirect the variant you do not use. Match canonical and sitemap URLs to the chosen style."},
            {"q": "Are Core Web Vitals a ranking factor?", "a": "They influence experience signals, especially competitive queries. Fast static pages often beat heavier CMS defaults without heroic optimization."},
        ],
        "internal_links": [
            {"url": "/guides/static-landing-page-playbook.html", "text": "Landing page playbook"},
            {"url": "/guides/cloudflare-pages-complete-guide.html", "text": "Cloudflare Pages guide"},
            {"url": "/how-to/", "text": "How-to articles"},
            {"url": "/tools/", "text": "SEO tools"},
            {"url": "/templates/", "text": "Templates index"},
        ],
        "cta": {
            "title": "Ship SEO-ready pages faster",
            "text": "Use templates with meta tags, OG images, and sitemap-friendly structure so you spend time on content—not boilerplate.",
            "url": "/templates/",
            "button": "Browse templates",
            "secondary_url": "/free-static-landing-kit/",
            "secondary_button": "Free static kit",
        },
    },
]